### PR TITLE
Add custom jsbin

### LINKED ISSUE #54: Add a customized jsbin for bug reports
The customized jsbin will need a url-bar element though, as jsbins run in iframe by default, so this is blocked by https://github.com/PolymerElements/carbon-route/issues/46

### PR DESCRIPTION
**Pull request by rictic**
Fixes #54

### CODE REVIEW

**Comment by chuckh** [comment]
LGTM

**Comment by TimvdLippe** [comment]
It seems that the defined `json` method is unused, is that intentional? Other than that LGTM!

**Comment by cdata** [comment]
LGTM 👍

**Comment by rictic** [comment]
Updated the jsbin to remove the unused `json` method. Nice catch!

**Pull request merged**
